name: CI Workflow

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Deps
        working-directory: site
        run: npm install

      - name: Running tests
        working-directory: site
        run: npm run test

      - name: Building Application
        working-directory: site
        run: npm run build

      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        working-directory: site
        run: npm run deploy