name: CI Workflow

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:

    name: Build Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Deps
        run: npm install


      - name: Running tests
        run: npm test
      
      - name: Building Application
        run: npm builds