name: CI Workflow

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:
    
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Deps
        working-directory: site
        run: npm install

      - name: Running tests
        working-directory: site
        run: npm test

      - name: Building Application
        working-directory: site
        run: npm builds