name: CI Workflow

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Deps
        working-directory: site
        run: npm install

      - name: Running tests
        working-directory: site
        run: npm run test

      - name: Building Application
        working-directory: site
        run: npm run build

      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        working-directory: site
        run: npm run deploy

      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}